//
//  Database.swift
//  test3
//
//  Created by Gauthier Clarisse on 06/02/2020.
//  Copyright © 2020 Gauthier Clarisse. All rights reserved.
//

import Foundation
import MapKit

//var landmarks =  [Landmark(id: EventType.tennis.rawValue, annotationType: .pin, name: "Match de tennis", location: CLLocationCoordinate2D(latitude: 50.633333, longitude: 3.066667)),
//                  Landmark(id: EventType.foot.rawValue, annotationType: .nativePin, name: "Match de football", location: CLLocationCoordinate2D(latitude: 50.687763, longitude: 3.175531))]
var events: [Event] = [Event(sportEvent : "Football",
                    prixEvent : "€€€€",
                    logoEvent: "⚽️",
                    nameEvent: "LOSC-PSG",
                    descriptionEvent: "La confrontation tant attendue entre les 2 meilleures attaques du championnat.",
                    siteEvent: "www.stade-pierre-mauroy.com",
                    dateEvent: "26/01/2020",
                    heureEvent: "21h",
                    lieuEvent: "Stade Pierre Mauroy",
                    imageEvent: "competfoot",
                    annotationType: .pin,
                    location: CLLocationCoordinate2D(latitude: 50.612178, longitude: 3.130511)),
              Event(sportEvent : "Tennis",
                    prixEvent : "€€€",
                    logoEvent: "🎾",
                    nameEvent: "Compétition de tennis",
                    descriptionEvent: "L'Equipe de France de Coupe Davis affronte la Suisse pour un remake de la finale de 2016.",
                    siteEvent: "www.losc.fr",
                    dateEvent: "21/02/2020",
                    heureEvent: "13h30",
                    lieuEvent: "Stade Pierre Mauroy",
                    imageEvent: "competennis",
                    annotationType: .tennis,
                    location: CLLocationCoordinate2D(latitude: 50.633333, longitude: 3.066667)),
              Event(sportEvent : "Football américain",
                    prixEvent : "€€",
                    logoEvent: "🏈",
                    nameEvent: "Match de foot US",
                    descriptionEvent: "Venez assister au match des Vikings de Villeneuve d'Ascq.",
                    siteEvent: "www.stadium-lillemetropole.fr",
                    dateEvent: "09/02/2020",
                    heureEvent: "17h30",
                    lieuEvent: "Stadium de Lille",
                    imageEvent: "americain",
                    annotationType: .footus,
                    location: CLLocationCoordinate2D(latitude: 50.6324857, longitude: 3.135222800000065)),
              Event(sportEvent : "Badminton",
                    prixEvent : "Gratuit",
                    logoEvent: "🏸",
                    nameEvent: "Compétition de badminton",
                    descriptionEvent: "Le club de Wasquehal enchaîne les victoires éclatantes en championnat ! Venez donc les voir pour les encourager !",
                    siteEvent: "www.wbc59.ovh",
                    dateEvent: "16/02/2020",
                    heureEvent: "14h30",
                    lieuEvent: "Club de badminton de Wasquehal",
                    imageEvent: "badminton",
                    annotationType: .bad,
                    location: CLLocationCoordinate2D(latitude: 50.677822, longitude: 3.126357)),
              Event(sportEvent : "Course à pied",
                    prixEvent : "€",
                    logoEvent: "🏃‍♂️",
                    nameEvent: "Semi-marathon de la braderie",
                    descriptionEvent: "Le traditionnel semi-marathon de la braderie de Lille réunira de nombreux aficionados de la course à pied. Venez nombreux !",
                    siteEvent: "www.braderie-de-lille.fr",
                    dateEvent: "31/08/2019",
                    heureEvent: "10h30",
                    lieuEvent: "Braderie de Lille",
                    imageEvent: "running",
                    annotationType: .run,
                    location: CLLocationCoordinate2D(latitude: 50.637011, longitude: 3.063907)),
              Event(sportEvent : "Basket-Ball",
                    prixEvent : "€€",
                    logoEvent: "⛹️‍♂️",
                    nameEvent: "Match de basketball du LMB",
                    descriptionEvent: "Le Lille Métropole Basket Club joue un match capital face à Denain dans le championnat de Pro B. Venez nombreux pour les encourager !",
                    siteEvent: "www.lmbc.fr",
                    dateEvent: "28/02/2020",
                    heureEvent: "20h",
                    lieuEvent: "Palais des sports Saint-Sauveur",
                    imageEvent: "basketball",
                    annotationType: .basket,
                    location: CLLocationCoordinate2D(latitude: 50.632868, longitude: 3.071887)),
              Event(sportEvent : "Hockey sur glace",
                    prixEvent : "€",
                    logoEvent: "🏒",
                    nameEvent: "Match de hockey sur glace des Lions de Wasquehal",
                    descriptionEvent: "Les Lions de Wasquehal jouent leur dernier match à domicile de la saison face à Valenciennes dans une ambiance survoltée.",
                    siteEvent: "www.leslionsdewasquehal.com",
                    dateEvent: "25/01/2020",
                    heureEvent: "18h40",
                    lieuEvent: "Patinoire Serge Charles",
                    imageEvent: "hockeyglace",
                    annotationType: .hockey,
                    location: CLLocationCoordinate2D(latitude: 50.677081, longitude: 3.123161)),
              Event(sportEvent : "Lancer de haches",
                    prixEvent : "€€",
                    logoEvent: "🪓",
                    nameEvent: "Lancer de haches",
                    descriptionEvent: "Prêts à vous défouler ? Alors découvrez le lancer de haches et venez en famille ou entre amis pour vous amuser.",
                    siteEvent: "www.lescognees.com",
                    dateEvent: "Toute l'année",
                    heureEvent: "Mardi-vendredi: 17h-22h, Samedi: 11h-22h et fermé le dimanche",
                    lieuEvent: "Les Cognées",
                    imageEvent: "lancerhache",
                    annotationType: .hache,
                    location: CLLocationCoordinate2D(latitude: 50.639518, longitude: 3.067695)),
              Event(sportEvent : "Judo",
                    prixEvent : "€€",
                    logoEvent: "🥋",
                    nameEvent: "Club de judo de Roubaix",
                    descriptionEvent: "Vous cherchez à pratiquer un art martial ? Venez essayer le judo au Judo Club Omnisports de Roubaix.",
                    siteEvent: "www.facebook.com/JCO-RBX-Officiel-Judo-Club-Omnisports-de-Roubaix-223562621170978",
                    dateEvent: "Toute l'année",
                    heureEvent: "Se renseigner auprès du club",
                    lieuEvent: "Salle Bernard Jeu",
                    imageEvent: "judoclub",
                    annotationType: .judo,
                    location: CLLocationCoordinate2D(latitude: 50.693378, longitude: 3.166549)),
              Event(sportEvent : "Bourle",
                    prixEvent : "Gratuit",
                    logoEvent: "🥋",
                    nameEvent: "Initiation à la bourle",
                    descriptionEvent: "Vous voulez découvrir un sport traditionnel de la région ? Alors venez nous en parler pour vous initier à la bourle.",
                    siteEvent: "www.fedbourlenord.wordpress.com/nos-bourloires/",
                    dateEvent: "Toute l'année",
                    heureEvent: "Se renseigner auprès de la fédération",
                    lieuEvent: "Siège de la Fédération Bourloire Cercle St Christophe",
                    imageEvent: "bourlefede",
                    annotationType: .bourle,
                    location: CLLocationCoordinate2D(latitude: 50.725541, longitude: 3.167551))
]

let recompenses = [
kdo(image: "chaussettes", name: "Chaussettes de foot", point: 500, description: "Le meilleur ami du footballeur, qu'il soit du dimanche ou professionnel."),
kdo(image: "tapis", name: "Tapis de fitness", point: 3000, description: "Un tapis de fitness pour toutes vos activités d'intérieur. Le meilleur moyen de maintenir une forme optimale."),
kdo(image: "haltères", name: "Haltères", point: 4500, description: "Vous voulez exhiber vos biceps sur la plage ? Pensez alors aux haltères pour travailler vos muscles du bras !"),
kdo(image: "gardien", name: "Ballon de football", point: 2000, description: "Persuadé d'être le nouveau Zidane ? Le ballon de football sera votre nouveau meilleur ami."),
kdo(image: "americain", name: "Ballon de foot US", point: 2500, description: "La finale du Super Bowl vous a inspiré ? Rien de plus simple ! Faites l'acquisition de ce ballon !"),
kdo(image: "sauter", name: "Corde à sauter", point: 1500, description: "\"Corde à sauter, hé hé, corde à sauter, hé hé !!\"L'objet idéal pour un cardio d'enfer !"),
kdo(image: "tennis", name: "Raquettes de tennis", point: 6000, description: "Appuyez et vous aurez peut-être les revers de Federer au bout d'un entraînement intensif."),
kdo(image: "running", name: "Chaussures de running", point: 10000, description: "Allez ! On oublie Netflix et le pot de Nutella et on se motive !"),
kdo(image: "mag", name: "Bon d'achat dans votre magasin bio", point: 2000, description: "Marre de la junk food ? Profitez de votre bon d'achat de 15€ pour decouvrir de nouvelles saveurs !"),
kdo(image: "magazine", name: "Abonnement à un magazine santé", point: 5000, description: "Soyez à la page avec votre magazine santé !"),
kdo(image: "yoga", name: "Séance d'initiation au yoga", point: 4000, description: "Un peu trop tendu ? Relaxez-vous au cours d'une séance de yoga unique."),
kdo(image: "hachee", name: "Initiation lancer de hache", point: 7500, description: "Marre des sports trop communs ? Decouvrez le lancer de hache au cours d'une initiation intense !")    ]

let myPoints = 500
